### ISSUE TITLE
[DB] service contracts

### ISSUE THREAD

**Issue by ranilplus** [ranilplus/Idac-Maintaenance#6]
Service contract id:
Start date:
End date:
Type:
Payment terms:
Status:in/expired

**Comment by ranilplus** [comment]
Notes: if any special details about contract

**Comment by AthulaDissanayaka** [comment]
I have spoken to Rohitha regarding service contracts. you need more information than 
in the table above. Follwong are some examples. So I think it is necessary to meet them once again before providing the service contract table. Let me know when we can meet. The agreement delays till next week because he has go some overseas suppliers.  
1. They need to keep the service contract history.
2. Service contract can be two years and first year can be free.

**Comment by ranilplus** [comment]
1. if customer continue service contract with same settings he/she can renew it there for we have to add last renewed date as a field and update End date.  All changes will recorded in log file with more details like who updated when then we can retrieve it when required. Or else we can close it and start new service contract with new Contract ID
2.  it is a type of  Service contract
